name: Video Generation and Upload Pipeline
on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:
  # Optional: Schedule runs
  # schedule:
  #   - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    # Set UTF-8 locale environment variables
    env:
      PYTHONIOENCODING: "utf-8"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg libsm6 libxext6 libxrender-dev libsndfile1 espeak-ng

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "jupyter>=1.0.0" "nbconvert>=5.6.1" "ipykernel>=6.0.0" "matplotlib>=3.4.0" "pandas>=1.2.0" "numpy>=1.20.0"
          python -m pip install "google-api-python-client>=2.0.2" "google-auth-httplib2>=0.0.4" "google-auth-oauthlib>=0.4.5"
          python -m pip install "pydub>=0.25.1" "moviepy>=1.0.3" "pillow>=8.1.0" "requests>=2.25.1"
          python -m pip install "papermill>=2.3.3" "opencv-python>=4.5.1" "dropbox>=11.6.0" "google-cloud-texttospeech>=2.4.0" "SpeechRecognition>=3.8.1" "pytube>=10.9.0" "beautifulsoup4>=4.9.3" "youtube-dl>=2021.1.16" "kokoro>=0.8.2" "soundfile>=0.10.3" "google-generativeai>=1.4.0" "yt-dlp>=2021.1.16"

      - name: Register ipykernel for current environment
        run: python -m ipykernel install --name=github-actions --display-name="Python 3 (github-actions)" --sys-prefix

      - name: Verify moviepy installation
        run: python -c "import moviepy.editor; print('moviepy is installed')"

      - name: Create necessary directories
        run: |
          mkdir -p Storage/temp_tweets \
                   Storage/temp_captions \
                   Storage/temp_audio \
                   Storage/music_library \
                   Storage/temp_images \
                   Video/final_videos

      - name: Set up credentials
        shell: bash
        run: |
          # Create a file containing your Dropbox token
          echo "${{ secrets.DROPBOX_ACCESS_TOKEN }}" > ~/.dropbox_token

      - name: Run Gemini/Ficción.ipynb
        run: papermill Gemini/Ficción.ipynb Gemini/Ficción_output.ipynb -k github-actions

      - name: Run Gemini/tweets.ipynb
        run: papermill Gemini/tweets.ipynb Gemini/tweets_output.ipynb -k github-actions

      - name: Run Gemini/captions.ipynb
        run: papermill Gemini/captions.ipynb Gemini/captions_output.ipynb -k github-actions

      - name: Run Creators/audio_tts.ipynb
        run: papermill Creators/audio_tts.ipynb Creators/audio_tts_output.ipynb -k github-actions

      - name: Run Creators/music_downloader.ipynb
        run: papermill Creators/music_downloader.ipynb Creators/music_downloader_output.ipynb -k github-actions

      - name: Run Creators/text_animator.ipynb
        run: papermill Creators/text_animator.ipynb Creators/text_animator_output.ipynb -k github-actions

      - name: Run Video/video_assembler.ipynb
        run: papermill Video/video_assembler.ipynb Video/video_assembler_output.ipynb -k github-actions

      - name: Upload videos to Dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: Video/final_videos
          dest: /videos

      - name: Upload tweet text files to Dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: Storage/temp_tweets
          dest: /text_files/tweets

      - name: Upload caption text files to Dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: Storage/temp_captions
          dest: /text_files/captions
