name: Video Generation and Upload Pipeline
on:
  # Trigger on push to main branch
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:
  # Optional: Schedule runs
  # schedule:
  #   - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    
    # Set UTF-8 locale environment variables
    env:
      PYTHONIOENCODING: "utf-8"
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg libsm6 libxext6 libxrender-dev libsndfile1 espeak-ng
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter nbconvert ipykernel matplotlib pandas numpy
          python -m pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
          python -m pip install pydub moviepy pillow requests
          python -m pip install papermill opencv-python dropbox google-cloud-texttospeech SpeechRecognition pytube beautifulsoup4 youtube-dl "kokoro>=0.8.2" soundfile google-generativeai yt-dlp
      
      - name: Register ipykernel for current environment
        run: python -m ipykernel install --name=github-actions --display-name="Python 3 (github-actions)" --sys-prefix
      
      - name: Verify moviepy installation
        run: python -c "import moviepy.editor; print('moviepy is installed')"
      
      - name: Create necessary directories
        run: |
          mkdir -p Storage/temp_tweets \
                   Storage/temp_captions \
                   Storage/temp_audio \
                   Storage/music_library \
                   Storage/temp_images \
                   Video/final_videos
      
      - name: Set up credentials
        shell: bash
        run: |
          # Create a file containing your Dropbox token
          echo "${{ secrets.DROPBOX_ACCESS_TOKEN }}" > ~/.dropbox_token
      
      - name: Run Gemini/Ficción.ipynb
        run: papermill Gemini/Ficción.ipynb Gemini/Ficción_output.ipynb -k github-actions
      
      - name: Run Gemini/tweets.ipynb
        run: papermill Gemini/tweets.ipynb Gemini/tweets_output.ipynb -k github-actions
      
      - name: Run Gemini/captions.ipynb
        run: papermill Gemini/captions.ipynb Gemini/captions_output.ipynb -k github-actions
      
      - name: Run Creators/audio_tts.ipynb
        run: papermill Creators/audio_tts.ipynb Creators/audio_tts_output.ipynb -k github-actions
      
      - name: Run Creators/music_downloader.ipynb
        run: papermill Creators/music_downloader.ipynb Creators/music_downloader_output.ipynb -k github-actions
      
      - name: Run Creators/text_animator.ipynb
        run: papermill Creators/text_animator.ipynb Creators/text_animator_output.ipynb -k github-actions
      
      - name: Run Video/video_assembler.ipynb
        run: papermill Video/video_assembler.ipynb Video/video_assembler_output.ipynb -k github-actions
      
      - name: Upload videos to Dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: Video/final_videos
          dest: /videos
      
      - name: Upload tweet text files to Dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: Storage/temp_tweets
          dest: /text_files/tweets
      
      - name: Upload caption text files to Dropbox
        uses: deka0106/upload-to-dropbox@v2
        with:
          dropbox_access_token: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          src: Storage/temp_captions
          dest: /text_files/captions
